#!/bin/bash
InstanceID=`curl -s "http://169.254.169.254/latest/meta-data/instance-id"`
ROLE=`aws --region us-east-1 ec2 describe-tags --filters Name=resource-id,Values=$InstanceID Name=key,Values=Role --output=text | awk {'print $5'}`

if [ $ROLE = "sdk" ]; then
        sh /etc/init.d/sdk stop
	rm -Rf /home/ec2-user/sdk/*
fi

if [ $ROLE = "webadmin" ]; then
        sh /etc/init.d/web stop
        rm -Rf /home/ec2-user/webadmin/*
fi

exit 0
